---@class GG.Test
---@field name string
---@field commits string[]
---@field expect string[]
---@field ignore? boolean

---@type GG.Test[]
return {
  {
    name = 'foo',
    commits = {
      'G D',
      'F C',
      'E C',
      'D AB',
      'C A',
      'B A',
      'A',
    },
    expect = {
      'G ',
      'd ',
      'D F ',
      'D c ',
      'D C E ',
      'D C c ',
      'D C   ',
      'a C   b ',
      'A C   B ',
      'A a   B ',
      'A A   B ',
      'A A   a ',
      'A       ',
    },
  },
  {
    name = 'bar',
    commits = {
      'F C',
      'E B',
      'D A',
      'C BA',
      'B A',
      'A',
    },
    expect = {
      'F ',
      'c ',
      'C E ',
      'C b ',
      'C B D ',
      'C B a ',
      'C B A ',
      'b B a ',
      'B   A ',
      'a   A ',
      'A     ',
    },
  },
  {
    name = 'bi-crossing 1',
    commits = {
      'J G',
      'I F',
      'H F',
      'G EB',
      'F D',
      'E A',
      'D A',
      'C A',
      'B A',
      'A',
    },
    expect = {
      'J ',
      'g ',
      'G I ',
      'G f ',
      'G F H ',
      'G F f ',
      'G F   ',
      'e F   b ',
      'E F   B ',
      'E d   B ',
      'E D   B ',
      'a D   B ',
      'A D   B ',
      'A a   B ',
      'A A C B ',
      'A A a B ',
      'A A A B ',
      'A A A a ',
      'A       ',
    },
  },
  {
    name = 'bi-crossing 2',
    commits = {
      'G C',
      'F D',
      'E C',
      'D CB',
      'C A',
      'B A ',
      'A',
    },
    expect = {
      'G ',
      'c ',
      'C F ',
      'C d ',
      'C D E ',
      'C D c ',
      'C D   ',
      'c b   ',
      'C B   ',
      'a B   ',
      'A B   ',
      'A a   ',
      'A     ',
    },
  },
  {
    name = 'strange 1',
    commits = {
      'G ADBEF',
      'F CADEB',
      'E DA',
      'D BC',
      'C BA',
      'B A',
      'A ',
    },
    expect = {
      'G ',
      'a d b e f ',
      'A D B E F ',
      'A d B e c a   b ',
      'A D B E C A   B ',
      'A D B d C a   B ',
      'A D B   C A   B ',
      'A c b   C A   B ',
      'A C B     A   B ',
      'A b B     a   B ',
      'A B       A     ',
      'A a       A     ',
      'A               ',
    },
  },

  {
    name = 'strange 2',
    commits = {
      'G BDECFA',
      'F BECAD',
      'E BAD',
      'D C',
      'C AB',
      'B A',
      'A ',
    },
    expect = {
      'G ',
      'b d e c f a ',
      'B D E C F A ',
      'B d e C b a c   ',
      'B D E C B A C   ',
      'B D d C b a C   ',
      'B D   C B A C   ',
      'B c   C B A C   ',
      'B C       A     ',
      'B b       a     ',
      'B         A     ',
      'a         A     ',
      'A               ',
    },
  },
  {
    name = 'branch out',
    commits = {
      'E AB',
      'D B',
      'C B',
      'B A',
      'A',
    },
    expect = {
      'E ',
      'a b ',
      'A B D ',
      'A B b ',
      'A B B C ',
      'A B B b ',
      'A B     ',
      'A a     ',
      'A       ',
    },
  },
  {
    name = 'branch in',
    commits = {
      'F B',
      'E BDC',
      'D A',
      'C A',
      'B A',
      'A',
    },
    expect = {
      'F ',
      'b ',
      'B E ',
      'B b d c ',
      'B B D C ',
      'B B a C ',
      'B B A C ',
      'B B A a ',
      'B   A A ',
      'a   A A ',
      'A       ',
    },
  },
  {
    name = 'ultra branch in',
    commits = {
      'H E',
      'G E',
      'F EDC',
      'E B',
      'D A',
      'C A',
      'B A',
      'A',
    },
    expect = {
      'H ',
      'e ',
      'E G ',
      'E e ',
      'E   F ',
      'e   d c ',
      'E   D C ',
      'b   D C ',
      'B   D C ',
      'B   a C ',
      'B   A C ',
      'B   A a ',
      'B   A A ',
      'a   A A ',
      'A       ',
    },
  },
  {
    name = 'alphred',
    commits = {
      'G DCBFE',
      'F E',
      'E D',
      'D CA',
      'C A',
      'B A',
      'A',
    },
    expect = {
      'G ',
      'd c b f e ',
      'D C B F E ',
      'D C B e E ',
      'D C B E   ',
      'D C B d   ',
      'D C B     ',
      'a c B     ',
      'A C B     ',
      'A a B     ',
      'A A B     ',
      'A A a     ',
      'A         ',
    },
  },

  {
    name = 'gustav',
    commits = {
      'G ABFCDE',
      'F DCEB',
      'E ACB',
      'D A',
      'C B',
      'B A',
      'A',
    },
    expect = {
      'G ',
      'a b f c d e ',
      'A B F C D E ',
      'A B b c d e ',
      'A B B C D E ',
      'A B B C D a c b ',
      'A B B C D A C B ',
      'A B B C a A C B ',
      'A B B C A A   B ',
      'A B B b A A   B ',
      'A B     A A     ',
      'A a     A A     ',
      'A               ',
    },
  },
  {
    name = 'frank',
    commits = {
      'G EAFDC',
      'F DEA',
      'E C',
      'D CA',
      'C B',
      'B A',
      'A',
    },
    expect = {
      'G ',
      'e a f d c ',
      'E A F D C ',
      'e A a d C ',
      'E A A D C ',
      'c A A D C ',
      'C A A D   ',
      'c A A a   ',
      'C A A A   ',
      'b A A A   ',
      'B A A A   ',
      'a A A A   ',
      'A         ',
    },
  },
  -- {
  --   name = 'short-frank',
  --   commits = {
  --     'G EAFDC',
  --     'F DEA',
  --     'E C',
  --     'D CA',
  --   },
  --   expect = {
  --     'G ',
  --     'e a f d c ',
  --     'E A F D C ',
  --     'e A a d C ',
  --     'E A A D C ',
  --     'c A A D C ',
  --     'C A A D   ',
  --   },
  -- },
  {
    name = 'julia',
    commits = {
      'G BFDEAC',
      'F ECBA',
      'E ACB',
      'D CA',
      'C B',
      'B A',
      'A',
    },
    expect = {
      'G ',
      'b f d e a c ',
      'B F D E A C ',
      'B b D e a c ',
      'B B D E A C ',
      'B B D a A c b ',
      'B B D A A C B ',
      'B B c a A C B ',
      'B B C A A   B ',
      'B B b A A   B ',
      'B     A A     ',
      'a     A A     ',
      'A             ',
    },
  },
  {
    name = 'letieu',
    commits = {
      'H CG',
      'G C',
      'F BE',
      'E BD',
      'D BA',
      'C B',
      'B A',
      'A',
    },
    expect = {
      'H ',
      'c g ',
      'C G ',
      'C c ',
      'C C F ',
      'C C b e ',
      'C C B E ',
      'C C B b d ',
      'C C B B D ',
      'C C B B b a ',
      'C   B B B A ',
      'b   B B B A ',
      'B         A ',
      'a         A ',
      'A           ',
    },
  },
  {
    name = 'different family',
    commits = {
      'H F',
      'G D',
      'F E',
      'E B',
      'D C',
      'C',
      'B A',
      'A',
    },
    expect = {
      'H ',
      'f ',
      'F G ',
      'F d ',
      'F D ',
      'e D ',
      'E D ',
      'b D ',
      'B D ',
      'B c ',
      'B C ',
      'B   ',
      'B   ',
      'a   ',
      'A   ',
    },
  },
}
